  ### GET All users:
GET http://localhost:8080/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1MTk0OH0.I_AKWHioPcOsZTfUt_oJzynTtDARY8cUsEngEweYT9M


### Get user:
GET http://localhost:8080/users/65c3e2a282ce5b2532e1b40b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1MTk0OH0.I_AKWHioPcOsZTfUt_oJzynTtDARY8cUsEngEweYT9M


### DELETE  user:
DELETE http://localhost:8080/users/65ea23528cafa2d89dfa58cf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1MTk0OH0.I_AKWHioPcOsZTfUt_oJzynTtDARY8cUsEngEweYT9M


### Add a user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "Regular@gmail.com",
  "name": {
    "first": "Regular",
    "last": "Regular"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "state": "ExampleState", 
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://www.theinterrobang.ca/images/interrobang/030819/B8QC6DAZ9PWRK7M2.jpg"
  },
  "phone": "0507777777",
  "isBusiness":false,
  "password": "123456cC!"
}


### POST request to verify a user
POST http://localhost:8080/users/verify
Content-Type: application/json

{
  "verificationCode": "T5AFzD"
}

### Request a new verification code
POST http://localhost:8080/users/request-new-code
Content-Type: application/json

{
  "email": "yaniv12033@gmail.com"  
}




###Edit Profile
PUT  http://localhost:8080/users/65e12aedb735c5d5d899569b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjVlMTJhZWRiNzM1YzVkNWQ4OTk1NjliIiwiaXNCdXNpbmVzcyI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDkyNTU0ODh9.CbpacYSknuT5r7byMLwDxFiUxukp4wSIYUtD-xx0ghc
Content-Type: application/json

{
  "name": {
    "first": "Willis",
    "last": "yaniv"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 69,
    "zip": "123456"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123090",
  "email": "admin@gmail.com",
  "isBusiness": false,
  "isAdmin": true,
  "password": "yaniv!123" 
}


### Login:
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "yaniv12033@gmail.com",
  "password": "yaniv!123"
}

### Login:
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456aA!"
}

###Edit Status
PATCH http://localhost:8080/users/6575ba245a440e0ca0aefa7b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjVlMTJhZWRiNzM1YzVkNWQ4OTk1NjliIiwiaXNCdXNpbmVzcyI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDkyNTU0MzR9.mfZBzi_g0c99MUsO_Pqq2ZbOuL0I2dkeqPiKMBa1Uh4
Content-Type: application/json

{
  "isBusiness": true
}

### order-confirmation
POST http://localhost:8080/users/order-confirmation
Content-Type: application/json
Accept: application/json

{
  "userEmail": "yaniv12033@gmail.com",
  "orderedCardIds": ["65da0a923bb22a2e60784a42"],
  "formData": {
    "DeliveryInformation": {
      "firstName": "John",
      "email": "yaniv12033@gmail.com",
      "lastName": "Doe",
      "address": "123 Main St",
      "city": "Cityville",
      "zipCode": "12345",
      "phone": "555-1234",
      "shippingMethod": "Standard"
    }
  }
}





### Submitting a Contact Form
POST http://localhost:8080/users/contact-us
Content-Type: application/json

{
  "name": "John Doe",
  "email": "yaniv12033@gmail.com",
  "message": "This is a test message"
}




### add a card: ### new card
POST http://localhost:8080/cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjViYmYyZGJlN2M3ODkzOGRhNWEwY2FlIiwiaXNCdXNpbmVzcyI6ZmFsc2UsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNjgxNjU3M30.hNbU-XFGKtkGvHdkMLAZ8tz2aSolwqT-Oqp9r7sfsXk
Content-Type: application/json

{
  "title": "MacBook Pro Laptop",
  "subtitle": "MacBook Pro",
  "description": "Apple 2023 MacBook Pro Laptop M3 chip with 8‑core CPU, 10‑core GPU: 14.2-inch Liquid Retina XDR Display, 8GB Unified Memory, 512GB SSD Storage. Works with iPhone/iPad; Space Gray",
  "brand":"Appel",
  "price": "1333",
  "shipping": "75",
  "images": [
    {
      "url": "https://m.media-amazon.com/images/I/61lsexTCOhL._AC_SX679_.jpg",
      "alt": "MacBook Pro Laptop"
    },
    {
      "url": "https://m.media-amazon.com/images/I/61RdWPq8UfL._AC_SX679_.jpg",
      "alt": "MacBook Pro Laptop"
    },
    {
      "url": "https://m.media-amazon.com/images/I/71mhIJSqKhL._AC_SX679_.jpg",
      "alt": "MacBook Pro Laptop"
    }
  ]
}


### Edit a Card
PUT http://localhost:8080/cards/65bcdb1ce2c4363217b79f8b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MzQxMzA0fQ.TS7bFTMV5nKx_IJsYC5Vbym0eWbpM9klIYPPLAlPzvY
Content-Type: application/json

{
 "title": "Card Title",
  "subtitle": "Card Subtitle",
  "description": "Card Description",
  "brand":"Apple",
  "price": "10.99",
  "shipping": "5.00",
  "images": [
    {
      "url": "https://m.media-amazon.com/images/I/71zRpbDLNLL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      "alt": "Image 1 Alt Text"
    },
    {
      "url": "https://m.media-amazon.com/images/I/61d+X4yl22L._AC_SX679_.jpg",
      "alt": "Image 1 Alt Text"
    }
  ]
}

### Get all cards:
GET http://localhost:8080/cards

### Get my-cards:
GET http://localhost:8080/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjk3NDMxNH0.9rxSVJKljg9si33a7qNMz-5wunk0CfmW7tjDLAQr8nk


### GET Card by id:
GET http://localhost:8080/cards/65a50edae95149f380ab50d9

### Delete a Card
DELETE http://localhost:8080/cards/6599772e88a27ad9a5e21f33
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU1ODQzfQ.PHJnLTQXYqC4nqT0CLQ-0egJOzlJS_WZLmshQ2RlqG8

### Request to Like a Card
PATCH http://localhost:8080/cards/65a5124c128978954177a3a1
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU1ODQzfQ.PHJnLTQXYqC4nqT0CLQ-0egJOzlJS_WZLmshQ2RlqG8

{
  "userId": "6599661d036ae1da45e585c7"
}




### Add to Cart
POST  http://localhost:8080/cards/65a5124c128978954177a3a1/add-to-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU2NzE1fQ.dtHaDafuEZju6wl086JuR2-cRwqT8LAyldKtCR3FODY


###forgot password
POST http://localhost:8080/users/forgot-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU2NzE1fQ.dtHaDafuEZju6wl086JuR2-cRwqT8LAyldKtCR3FODY

 {
  "email": "yaniv12033@gmail.com"
}



###Reset Password:
POST  http://localhost:8080/users/reset-password/65c3e2a282ce5b2532e1b40b/95e6cae5f04c6e3512e182ed6cf6fa639989bbaf8df0e27a77a53f49b9ccc481
Content-Type: application/json

{
"password": "Aa123456!!"
}



### Update User Profile with Image Upload ###

PUT http://localhost:8080/users/65e12aedb735c5d5d899569b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjVlMTJhZWRiNzM1YzVkNWQ4OTk1NjliIiwiaXNCdXNpbmVzcyI6ZmFsc2UsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwOTI5Mzc1M30.c4emIsVee3y6pQMUp1eosbfPcocD3eUEnBZtoHyvJdo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryABC123

------WebKitFormBoundaryABC123
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

@C:/Users/maida/Downloads/1293438.jpg
------WebKitFormBoundaryABC123--




